version: 0.2
phases:
  install:
    commands:
      - "apt-get install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.2.0/terraform_1.2.0_linux_amd64.zip"
      - "unzip terraform_1.2.0_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform $TF_COMMAND -auto-approve

  post_build:
    commands:
      - echo terraform $TF_COMMAND completed on
